### ISSUE TITLE
model.pt error

### ISSUE THREAD

**Issue by biotech70** [HeliXonProtein/binding-ddg-predictor#5]
during binding-ddg-predictior, I got the below error. model.pt file exists in the data directory.
![1](https://user-images.githubusercontent.com/73783725/188270178-0c3895cf-c806-4db7-a10f-1754ac35c155.png)
![2](https://user-images.githubusercontent.com/73783725/188270185-6f94332a-0416-4b54-8623-dcf961d524d5.png)

**Comment by luost26** [comment]
Hi,

Thank you for your interest in our project.

Could you try change your working directory to `~/binding-ddg-predictor` and run the following command:
```
python ./scripts/predict.py ./data/example_wt.pdb ./data/example_mut.pdb
```

Thanks!

**Comment by biotech70** [comment]
thanks, the problem has been solved. what is the formula of ddg calculation in your tools? ddg=dgmut - dgwild or dgwild -dgmut
