### ISSUE TITLE
how  binding-ddg-predictor calculate ddg?

### ISSUE THREAD

**Issue by biotech70** [HeliXonProtein/binding-ddg-predictor#6]
Hi, which one of the following formulae use in binding-ddg-predictor for ddg calculation?
1- ddg = dg/mutant - dg/wild
or
2- ddg = dg/wild - dg/mutant

**Comment by biotech70** [comment]
I need your help since I can't find any tutorial about your tools and the method of ddg calculation.

**Comment by luost26** [comment]
Hi,

We used ddg = dg/mutant - dg/wild.
